[connections.postgresql]
dialect = "postgresql"
host = "127.0.0.1"
port = "5432"
database = "postgres"
username = "postgres"
password = "postgres"

[postgres]
host = "127.0.0.1"
database = "postgres"
user = "postgres"
password = "postgres"